### ISSUE TITLE
Uglify multiple files into one

### ISSUE THREAD

**Issue by spyropress** [sindresorhus/atom-uglify#10]
Hi,

I want to uglify multiple files into one

//uglify-js out: out/file.js, files: file-1.js file-2.js file-3.js, compress: true

is it possible with your package.

Thanks in advance

**Comment by sindresorhus** [comment]
That's outside the scope of this package. You're better off using a build system for that.

**Comment by spyropress** [comment]
Hi,

can you help me get this running as there is some old code which not let it run and I want it badly otherwise for just this purpose I have to use gruntjs. Thats from a programmer to a programmer.

https://github.com/cfv1984/js-joiner

Thanks

**Comment by sindresorhus** [comment]
http://stackoverflow.com/a/8812680/64949

**Comment by spyropress** [comment]
@sindresorhus that's great but I don't want to leave the Atom window. If js-joiner can be fixed all will be done using it.

Command prompt means you have to type or paste the command everytime..
